version: '3.8'

services:
  # --- 1. INFRASTRUCTURA (Porturile tale CUSTOM) ---

  rabbitmq:
    image: rabbitmq:3-management
    container_name: festflow-rabbitmq
    ports:
      - "8672:5672"
      - "18672:15672"
    networks:
      - festflow-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: festflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - festflow-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: festflow-kafka
    depends_on:
      - zookeeper
    ports:
      - "8092:8092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Conexiuni: Extern pe 8092, Intern pe 29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:8092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - festflow-network

  db:
    image: postgres:15
    container_name: festflow-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: festflow
    ports:
      - "8432:5432"
    networks:
      - festflow-network

  # --- 2. SERVICIILE TALE PYTHON ---

  order-service:
    build: ./order-service
    container_name: order-service
    restart: always  # <--- FORTEAZA REPORNIREA DACA CRAPA
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_URL=postgresql://user:password@db:5432/festflow
    networks:
      - festflow-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    restart: always  # <--- ESENTIAL: Daca nu se conecteaza la Kafka, incearca iar, nu dispare
    depends_on:
      - rabbitmq
      - kafka
      - db
    environment:
      - RABBITMQ_HOST=rabbitmq
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092 # Portul intern corect
      - DATABASE_URL=postgresql://user:password@db:5432/festflow
    networks:
      - festflow-network

  email-service:
    build: ./email-service
    container_name: email-service
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - festflow-network

  # --- 3. GATEWAY ---

  nginx:
    image: nginx:latest
    container_name: festflow-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - order-service
    networks:
      - festflow-network

# --- 4. RETEAUA COMUNA ---
networks:
  festflow-network:
    driver: bridge